name: "Create PR in external repo using GH CLI"

on:
  pull_request:
    types: [closed]

jobs:
  createExternalPR:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.body, '[SYNC_TO_CHILD]')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Setup GitHub CLI
        run: |
          bash external_pr_files/setup_cli.sh

      - name: Clone target repository
        run: |
          bash external_pr_files/clone_target_repo.sh
        env:
          GH_TOKEN: ${{ secrets.TARGET_REPO_PAT }}

      - name: Create label if not exists
        run: |
          bash external_pr_files/create_label.sh
        env:
          GH_TOKEN: ${{ secrets.TARGET_REPO_PAT }}

      - name: Check if PR already exists and update branch
        run: |
          bash external_pr_files/check_pr_and_update_branch.sh "${{ github.event.repository.name }}"
        env:
          GH_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
          GITHUB_SHA: ${{ github.event.pull_request.merge_commit_sha }}
          GITHUB_ACTOR: ${{ github.event.pull_request.user.login }}

      - name: Create or update Pull Request
        run: |
          bash external_pr_files/create_or_update_pr.sh "${{ github.event.repository.name }}"
        env:
          GH_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
          GITHUB_SHA: ${{ github.event.pull_request.merge_commit_sha }}
          GITHUB_ACTOR: ${{ github.event.pull_request.user.login }}
