name: "Create PR in external repo using GH CLI"

on:
  push:
    branches:
      - '**'

jobs:
  createExternalPR:
    runs-on: ubuntu-latest
#    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Generate report file
        run: date "+%Y-%m-%d %H:%M" > report.txt

      - name: Setup GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Clone target repository
        run: |
          git clone https://${{ secrets.TARGET_REPO_PAT }}@github.com/QuietHellsPage/Testing-repository.git
          cp report.txt Testing-repository/
          cd Testing-repository
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create branch and commit changes
        run: |
          cd Testing-repository
          git checkout -b automated-update-${{ github.sha }}
          git add report.txt
          git commit -m "Update report from ${{ github.repository }}"
          git push origin automated-update-${{ github.sha }}

      - name: Create label if not exists
        run: |
          cd Testing-repository
          if ! gh label view "automated pr" --repo QuietHellsPage/Testing-repository 2>/dev/null; then
            gh label create "automated pr" --color "0E8A16" --description "Automated pull request" --repo QuietHellsPage/Testing-repository
          fi
        env:
          GH_TOKEN: ${{ secrets.TARGET_REPO_PAT }}

      - name: Create Pull Request using GH CLI
        run: |
          cd Testing-repository
          gh pr create \
            --repo QuietHellsPage/Testing-repository \
            --head automated-update-${{ github.sha }} \
            --base main \
            --title "[Automated] PR from ${{ github.repository }}" \
            --body "Automated update from ${{ github.repository }}
            
            Generated at: $(date)
            Source commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}" \
            --label "automated pr" \
            --assignee QuietHellsPage \
            --reviewer QuietHellsPage
        env:
          GH_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
